### ISSUE TITLE
loading error

### ISSUE THREAD

**Issue by RyosukeCla** [akameco/electron-load-devtool#2]
Error:
Skip loading 'React Developer Tools' because it can't be found. Please install at Chrome Web Store.
opened!

Thank you for your tool.
I have one idea that may improve your tool.

Your electron-load-devtool supports only one path to google extensions. By default, the path of google extensions is "Chrome/Default/Extensions/", but this path can be changed to another path like "Chrome/Profile1/Extenions/".

So I think that this tool should have more options. I am happy if you think that my idea is good.

**Comment by akameco** [comment]
Good point.
I added `profile` option.
Thank you, @RyosukeCla :)
