### ISSUE TITLE
UbuntuにSnapでインストールしたChromiumに対応していない

### ISSUE THREAD

**Issue by yskkin** [akameco/electron-load-devtool#6]
- version:1.1.0
- `node` version:  v11.6.0
- `npm` (or `yarn`) version: yarn 1.12.3

**Do you want to request a _feature_ or report a _bug_?:**
バグ

**What is the current behavior?:**
UbuntuにSnapでインストールしたChromiumに対応していない

**What is the expected behavior?:**

`loadDevTool(loadDevTool.REACT_DEVELOPER_TOOLS, {name: 'chromium'});`
としてもelectron上にReactのタブが表示されない。

**Suggested solution:**
Snap版をインストールした場合、`~/.config`ではなく、`~/.config/snap/chromium/current/.config`
以下に拡張機能が保存されるようなので、以下のようにするとローカルでは動作しました。

問題なさそうであればプルリク出します。

```
diff --git a/index.js b/index.js
index 5ed4213..7f72f91 100644
--- a/index.js
+++ b/index.js
@@ -35,7 +35,11 @@ const windows = profile => {
 
 const linux = (chrome, profile) => {
   chrome = chrome || 'google-chrome'
-  return path.join(homedir, '.config', chrome, profile, 'Extensions')
+  const candidates = [
+    path.join(homedir, '.config', chrome, profile, 'Extensions'),
+    path.join(homedir, 'snap', chrome, 'current', '.config', chrome, profile, 'Extensions')
+  ]
+  return candidates.find(path => fs.existsSync(path));
 }
```

**Comment by akameco** [comment]
@yskkin Issueありがとうございます。Snap版がどこにインストールされるのか、なにか公式の資料等があれば共有お願いします？ 自分がUbuntuを使っていないのでそれだけ確認しておきたいです。

**Comment by yskkin** [comment]
使うだけだったのでよく分かっていないのですが、

https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1575053
https://forum.snapcraft.io/t/change-home-snap-to-snap/1827

で ~/snap から ~/.snap 等に変えたいという話があるようですが、
 ~/snap 自体に関する記載については探せませんでした。

将来変わりうるものなら、prefixオプション等を新設して外から指定できるようにした方がいいのかもしれないです。

**Comment by akameco** [comment]
@yskkin あまりオプション取りたくないので、将来の対応はそのときに考えることにします。それと既存の動きを壊さないので問題なさそうです。diffのコードで問題なさそうなのでPRお願いできますか？
